//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEquipment
    {
        public int id { get; set; }
        public int id_Car { get; set; }
        public int id_TypeEquipment { get; set; }
        public string nameEquipment { get; set; }
        public string descriptionEquipment { get; set; }
        public decimal price { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
    }
}
